### ISSUE TITLE
Port 00 Boiler plate from TS to JS (ES6 > ES6)

### ISSUE THREAD

**Issue by brauliodiez** [Lemoncode/react-by-sample-es6#1]
I have assigned this case to @hithwen

Port the sample from:

https://github.com/Lemoncode/react-by-sample/tree/master/00%20Boilerplate

Create the same folder and structure in this project.

Changes to introduce:
- Rename main.ts from ts to js.
- Change the content of main.js to make use of some ES6 feature (just to ensure we are translating in the right way), you can take a sample from https://github.com/Lemoncode/webpack-1.x-by-sample/blob/master/00%20Intro/00%20BoilerPlate/students.js
- Remove the typescript loader (and webpack entry for that), add babel support.

Working with babel is not straight forward (you will have to install several packages to make it work), you can get the right list of package plus webpack config from here: https://github.com/Lemoncode/webpack-1.x-by-sample/tree/master/00%20Intro/00%20BoilerPlate

**Comment by hithwen** [comment]
To much JIRA, I expected the issue to close by itself -.-
